### **IMDB Movie Reviews Classification**

#### **Memakai Linear SVC dan Naive Bayes Model**

##### **Import Library**

In [ ]:
!pip install jcopml

##### **Import Library and Dataset**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
imdb = pd.read_csv('IMDB Dataset.csv')
imdb.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
imdb.shape

(50000, 2)

In [ ]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [ ]:
imdb['sentiment'].value_counts()

negative    25000
positive    25000
Name: sentiment, dtype: int64

Kita akan mengambil 1 sample dan melihat mengapa kita harus melakukan cleaning pada teks

### **Contoh review pada index 0**

In [ ]:
review = imdb['review'][0]
review

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

Pada umumnya, NLP task meliputi teknik text cleaning sebagai berikut

1. Menghilangkan konten HTML seperti '<br>'
2. Menghilangkan tanda baca, karakter spesial seperti '/'
3. Menghilangkan stopwords
4. Stemming / Lemmatization
5. Vectorization - encode nilai numerikal setelah dilakukan cleaning text
6. Fit data ke dalam model machine learning

#### **Menghilangkan konten HTML**

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
bsoup = BeautifulSoup(review, 'html.parser')
review = bsoup.get_text()
review

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

Dapat terlihat bahwa konten HTML telah dihilangkan


Berikutnya kita akan menghilangkan tulisan lower / upper case dengan regular expression

In [ ]:
import re

In [ ]:
review = re.sub('\[[^]]*\]', ' ', review)
review = re.sub('[^a-zA-Z]', ' ', review)
review

'One of the other reviewers has mentioned that after watching just   Oz episode you ll be hooked  They are right  as this is exactly what happened with me The first thing that struck me about Oz was its brutality and unflinching scenes of violence  which set in right from the word GO  Trust me  this is not a show for the faint hearted or timid  This show pulls no punches with regards to drugs  sex or violence  Its is hardcore  in the classic use of the word It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary  It focuses mainly on Emerald City  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  Em City is home to many  Aryans  Muslims  gangstas  Latinos  Christians  Italians  Irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away I would say the main appeal of the show is due to the fact that it goes where other shows wo

Berikutnya kita akan mengatur agar semua huruf menjadi lowercase

In [ ]:
review = review.lower()
review

'one of the other reviewers has mentioned that after watching just   oz episode you ll be hooked  they are right  as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence  which set in right from the word go  trust me  this is not a show for the faint hearted or timid  this show pulls no punches with regards to drugs  sex or violence  its is hardcore  in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wo

Berikutnya kita akan menghilangkan Stopwords - proses menghilangkan Stopwords bekerja untuk setiap kata dalam teks sehingga kita harus split textnya

In [ ]:
review = review.split()
review

['one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 'oz',
 'episode',
 'you',
 'll',
 'be',
 'hooked',
 'they',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'me',
 'the',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'go',
 'trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'this',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'word',
 'it',
 'is',
 'called',
 'oz',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'it',
 'focuses',
 'mainly',
 'on',
 '

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
review = [word for word in review if not word in set(stopwords.words('english'))]
review

['one',
 'reviewers',
 'mentioned',
 'watching',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'many',
 'aryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'away',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'dare',
 

Berikutnya kita akan melakukan Stemming / Lemmatization - kita akan lakukan keduanya dan lihat perbedaanya

In [ ]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
review_stem = [ps.stem(word) for word in review]
review_stem

['one',
 'review',
 'mention',
 'watch',
 'oz',
 'episod',
 'hook',
 'right',
 'exactli',
 'happen',
 'first',
 'thing',
 'struck',
 'oz',
 'brutal',
 'unflinch',
 'scene',
 'violenc',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'heart',
 'timid',
 'show',
 'pull',
 'punch',
 'regard',
 'drug',
 'sex',
 'violenc',
 'hardcor',
 'classic',
 'use',
 'word',
 'call',
 'oz',
 'nicknam',
 'given',
 'oswald',
 'maximum',
 'secur',
 'state',
 'penitentari',
 'focus',
 'mainli',
 'emerald',
 'citi',
 'experiment',
 'section',
 'prison',
 'cell',
 'glass',
 'front',
 'face',
 'inward',
 'privaci',
 'high',
 'agenda',
 'em',
 'citi',
 'home',
 'mani',
 'aryan',
 'muslim',
 'gangsta',
 'latino',
 'christian',
 'italian',
 'irish',
 'scuffl',
 'death',
 'stare',
 'dodgi',
 'deal',
 'shadi',
 'agreement',
 'never',
 'far',
 'away',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goe',
 'show',
 'dare',
 'forget',
 'pretti',
 'pictur',
 'paint',
 'mainstream',
 '

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lem = WordNetLemmatizer()
review_lemma = [lem.lemmatize(word) for word in review]
review_lemma

['one',
 'reviewer',
 'mentioned',
 'watching',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scene',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pull',
 'punch',
 'regard',
 'drug',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focus',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cell',
 'glass',
 'front',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'em',
 'city',
 'home',
 'many',
 'aryan',
 'muslim',
 'gangsta',
 'latino',
 'christian',
 'italian',
 'irish',
 'scuffle',
 'death',
 'stare',
 'dodgy',
 'dealing',
 'shady',
 'agreement',
 'never',
 'far',
 'away',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'go',
 'show',
 'dare',
 'forget',
 'pretty',
 'p

Dapat kita lihat bahwa kata 'little' menjadi 'littl' setelah Stemming tetapi tetap menjadi 'little' setelah Lemmatization. Maka kita akan gunakan Lemmatization

Menggabungkan kata kata yang telah di cleaned

In [ ]:
review_cleaned = ' '.join(review)
review_cleaned

'one reviewers mentioned watching oz episode hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home many aryans muslims gangstas latinos christians italians irish scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows dare forget pretty pictures painted mainstream audiences forget charm forget romance oz mess around first episode ever saw struck nasty surreal say ready watched developed taste oz got accustomed high levels graphic violence violence injustice crooked guards sold nickel inmates kill order get away well mannered middle class inmates turned prison bitches due lack street skill

Langkah berikutnya kita akan membentuk format matematikal pada teks ini dan untuk melakukan itu kita akan membuat corpus

In [ ]:
corpus = []
corpus.append(review_cleaned)

Berikutnya kita akan melakukan Vectorization. Ada 2 macam vectorization :

1. Count Vectorizer (Bag of Words Model)
2. TfIdf Vectorizer (Bag of Words Model)
3. Keras Tokenizer (Embedding)

###### **Count Vectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()
review_cv = cv.fit_transform(corpus)
review_cv.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1,
        2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 1,
        1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1,
        1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 2,
        1, 2, 1]])

Dapat kita lihat bahwa data telah berubah menjadi numerikal dengan nilai 1, 2, 3s tergantung dari berapa kali mereka muncul dalam teks

Ada variasi lain dari Count Vectorizer dengan binary=True dan pada kasus itu, semua zero entry akan bernilai 1

In [ ]:
cv_bin = CountVectorizer(binary=True)
review_cv_bin = cv_bin.fit_transform(corpus)
review_cv_bin.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

Tidak ada no 2s dan 3s dalam vektor

Berikutnya kita akan memakai TF-IDF (Text Frequency - Inverse Document Frequency) Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()
review_tfidf = tfidf.fit_transform(corpus)
review_tfidf.toarray()

array([[0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.12700013, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.12700013, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.12700013, 0.06350006, 0.06350006,
        0.12700013, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.12700013,
        0.06350006, 0.19050019, 0.06350006, 0.06350006, 0.12700013,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.12700013, 0.06350006, 0.06350006, 0.06350006, 0.12700013,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06350006, 0.06350006,
        0.06350006, 0.06350006, 0.06350006, 0.06

Sekarang akan menerapkan semua teknik yang telah terapkan tadi tapi tidak ada dataset testing sehingga kita akan membuat dataset test sebesar 25% dari dataset

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
dataset_train, dataset_test, train_data_label, test_data_label = train_test_split(imdb['review'], imdb['sentiment'], test_size=0.25, random_state=42)

In [ ]:
print(dataset_train.shape)
print(dataset_test.shape)
print(train_data_label.shape)
print(test_data_label.shape)

(37500,)
(12500,)
(37500,)
(12500,)


Konversi sentimen menjadi bentuk numerikal

In [ ]:
train_data_label = (train_data_label.replace({'positive' : 1, 'negative' : 0})).values
test_data_label = (test_data_label.replace({'positive' : 1, 'negative' : 0})).values

Kita akan melakukan cleaning teks dan membuat training dan testing corpus

In [ ]:
corpus_train = []
corpus_test = []

In [ ]:
for i in range(dataset_train.shape[0]):
  soup = BeautifulSoup(dataset_train.iloc[i], 'html.parser')
  review = soup.get_text()
  review = re.sub('\[[^]]*\]', ' ', review)
  review = re.sub('[^a-zA-Z]', ' ', review)
  review = review.lower()
  review = review.split()
  review = [word for word in review if not word in set(stopwords.words('english'))]
  lem = WordNetLemmatizer()
  review = [lem.lemmatize(word) for word in review]
  review = ' '.join(review)
  corpus_train.append(review)

In [ ]:
for j in range(dataset_test.shape[0]):
    soup = BeautifulSoup(dataset_test.iloc[j], "html.parser")
    review = soup.get_text()
    review = re.sub('\[[^]]*\]', ' ', review)
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    lem = WordNetLemmatizer()
    review = [lem.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus_test.append(review)

Kita lakukan validasi terhadap salah satu sampel

In [ ]:
corpus_train[0]

'figure alternate reality teen flick precisely ferris bueller type character leader cheat ring yeah know meant compared ferris bueller least orange orange way none le bottom line galaxy away even even minor classic watchable though expecting much said main character charm premise wear thin writing clever movie deliver enough laugh twist tension keep interest honest continue watching watching hope see anything suddenly clicked stylish recommend movie btw seems odd see mary tyler moore principal truly miscast hope paycheck inordinately big'

In [ ]:
corpus_test[0]

'really liked summerslam due look arena curtain look overall interesting reason anyways could one best summerslam ever wwf lex luger main event yokozuna time ok huge fat man v strong man glad time changed terrible main event like every match luger terrible match card razor ramon v ted dibiase steiner brother v heavenly body shawn michael v curt hening event shawn named big monster body guard diesel irs v kid bret hart first take doink take jerry lawler stuff hart lawler always interesting ludvig borga destroyed marty jannetty undertaker took giant gonzalez another terrible match smoking gunns tatanka took bam bam bigelow headshrinkers yokozuna defended world title lex luger match boring terrible ending however deserves'

Kita akan lakukan vectorization

###### **Tf-Idf Vectorizer**

In [ ]:
tfidf_vec = TfidfVectorizer(ngram_range=(1, 3))

tfidf_vec_train = tfidf_vec.fit_transform(corpus_train)
tfidf_vec_test = tfidf_vec.transform(corpus_test)

###### **Count Vectorizer (binary=False)**

In [ ]:
count_vec = CountVectorizer(ngram_range=(1, 3), binary=False)
count_vec_train = count_vec.fit_transform(corpus_train)
count_vec_test = count_vec.transform(corpus_test)

###### **Count Vectorizer (binary=True)**

In [ ]:
count_vec_true = CountVectorizer(ngram_range=(1, 3), binary=True)
count_vec_true_train = count_vec_true.fit_transform(corpus_train)
count_vec_true_test = count_vec_true.transform(corpus_test)

##### **First model : Linear SVC (Tf-Idf Vectorizer)**

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
linear_svc = LinearSVC(C=0.5, random_state=42)
linear_svc.fit(tfidf_vec_train, train_data_label)
predict_svc = linear_svc.predict(tfidf_vec_test)

Kita lihat performanya

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
print('Classification Report for Linear SVC Model Using Tf-Idf Vectorizer: \n\n', classification_report(test_data_label, predict_svc, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Linear SVC Model Using Tf-Idf Vectorizer: \n', confusion_matrix(test_data_label, predict_svc))
print()
print('Model Accuracy for Linear SVC Model Using Tf-Idf Vectorizer:', accuracy_score(test_data_label, predict_svc))

Classification Report for Linear SVC Model Using Tf-Idf Vectorizer: 

               precision    recall  f1-score   support

    Negative       0.91      0.89      0.90      6157
    Positive       0.89      0.92      0.91      6343

    accuracy                           0.90     12500
   macro avg       0.90      0.90      0.90     12500
weighted avg       0.90      0.90      0.90     12500

Confusion Matrix for Linear SVC Model Using Tf-Idf Vectorizer: 
 [[5467  690]
 [ 524 5819]]

Model Accuracy for Linear SVC Model Using Tf-Idf Vectorizer: 0.90288


##### **Second Model : Linear SVC (Count Vectorizer with binary = False)**

In [ ]:
linear_svc_count = LinearSVC(C=0.5, random_state=42, max_iter=5000)
linear_svc_count.fit(count_vec_train, train_data_label)
predict_svc_count = linear_svc_count.predict(count_vec_test)

Kita lihat performanya

In [ ]:
print('Classification Report for Linear SVC Model Using Count Vectorizer (binary=False):\n\n', classification_report(test_data_label, predict_svc_count, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Linear SVC Model Using Count Vectorizer (binary=False):\n', confusion_matrix(test_data_label, predict_svc_count))
print()
print('Model Accuracy for Linear SVC Model Using Count Vectorizer (binary=False): ', accuracy_score(test_data_label, predict_svc_count))

Classification Report for Linear SVC Model Using Count Vectorizer (binary=False):

               precision    recall  f1-score   support

    Negative       0.90      0.89      0.90      6157
    Positive       0.90      0.90      0.90      6343

    accuracy                           0.90     12500
   macro avg       0.90      0.90      0.90     12500
weighted avg       0.90      0.90      0.90     12500

Confusion Matrix for Linear SVC Model Using Count Vectorizer (binary=False):
 [[5489  668]
 [ 611 5732]]

Model Accuracy for Linear SVC Model Using Count Vectorizer (binary=False):  0.89768


##### **Third Model : Linear SVC (Count Vectorizer with binary = True)**

In [ ]:
linear_svc_count_true = LinearSVC(C=0.5, random_state=42)
linear_svc_count_true.fit(count_vec_true_train, train_data_label)
predict_svc_count_true = linear_svc_count_true.predict(count_vec_true_test)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Kita lihat performanya

In [ ]:
print('Classification Report for Linear SVC Model Using Count Vectorizer (binary=False): \n\n', classification_report(test_data_label, predict_svc_count_true, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Linear SVC Model Using Count Vectorizer (binary=False): \n', confusion_matrix(test_data_label, predict_svc_count_true))
print()
print('Model Accuracy for Linear SVC Model Using Count Vectorizer (binary=True): ', accuracy_score(test_data_label, predict_svc_count_true))

Classification Report for Linear SVC Model Using Count Vectorizer (binary=False): 

               precision    recall  f1-score   support

    Negative       0.90      0.89      0.89      6157
    Positive       0.89      0.90      0.90      6343

    accuracy                           0.89     12500
   macro avg       0.89      0.89      0.89     12500
weighted avg       0.89      0.89      0.89     12500

Confusion Matrix for Linear SVC Model Using Count Vectorizer (binary=False): 
 [[5461  696]
 [ 621 5722]]

Model Accuracy for Linear SVC Model Using Count Vectorizer (binary=True):  0.89464


Nilai Akurasi Tertinggi didapat dengan model **Linear SVC memakai Tf-Idf Vectorizer**

Berikutnya kita akan memakai Multinomial Naive Bayes Classifier

**Tf-Idf Vectorizer**

In [ ]:
tfidf_nb_multi = TfidfVectorizer(ngram_range=(1, 1))
tfidf_nb_multi_train = tfidf_nb_multi.fit_transform(corpus_train)
tfidf_nb_multi_test = tfidf_nb_multi.transform(corpus_test)

Terdapat 81301 kolom dalam corpus, sehingga kita akan gunakan test Chi-Square untuk mengambil 50000 kolom (features) saja

**Count Vectorizer (binary = False)**

In [ ]:
count_multi_nb = CountVectorizer(ngram_range=(1, 3), binary=False)
count_multi_nb_train = count_multi_nb.fit_transform(corpus_train)
count_multi_nb_test = count_multi_nb.transform(corpus_test)

**Count Vectorizer (binary = True)**

In [ ]:
count_multi_nb_true = CountVectorizer(ngram_range=(1, 3), binary=True)
count_multi_nb_true_train = count_multi_nb_true.fit_transform(corpus_train)
count_multi_nb_true_test = count_multi_nb_true.transform(corpus_test)

##### **Fourth Model : Multinomial Naive Bayes (Tf-Idf Vectorizer)**

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2

In [ ]:
ch2 = SelectKBest(chi2, k=50000)
tfidf_nb_multi_train = ch2.fit_transform(tfidf_nb_multi_train, train_data_label)
tfidf_nb_multi_test = ch2.transform(tfidf_nb_multi_test)

Sekarang kita bisa melihat featuresnya

In [ ]:
features_names = tfidf_nb_multi.get_feature_names()
features_names

['aa',
 'aaa',
 'aaaaaaaaaaaahhhhhhhhhhhhhh',
 'aaaaaaaargh',
 'aaaaagh',
 'aaaaah',
 'aaaaahhhh',
 'aaaaargh',
 'aaaaatch',
 'aaaaaw',
 'aaaahhhhhh',
 'aaaahhhhhhh',
 'aaaarrgh',
 'aaaawwwwww',
 'aaah',
 'aaahhhhhhh',
 'aaam',
 'aaand',
 'aaargh',
 'aaaugh',
 'aab',
 'aachen',
 'aada',
 'aadha',
 'aag',
 'aage',
 'aaghh',
 'aah',
 'aahed',
 'aahhhh',
 'aahing',
 'aaila',
 'aailiyah',
 'aaja',
 'aajala',
 'aake',
 'aaker',
 'aalcc',
 'aaliyah',
 'aalox',
 'aames',
 'aamir',
 'aamr',
 'aamto',
 'aan',
 'aankh',
 'aankhen',
 'aap',
 'aapke',
 'aapkey',
 'aaran',
 'aardman',
 'aardvark',
 'aarf',
 'aargh',
 'aarika',
 'aaron',
 'aaronanchors',
 'aashok',
 'aasmaan',
 'aasman',
 'aatish',
 'aaton',
 'aau',
 'aauugghh',
 'aavjo',
 'aawip',
 'aaww',
 'ab',
 'aba',
 'ababy',
 'aback',
 'abadi',
 'abagail',
 'abanazer',
 'abandon',
 'abandoned',
 'abandoning',
 'abandoningindian',
 'abandonment',
 'abandonof',
 'abanks',
 'abashed',
 'abashidze',
 'abasing',
 'abatement',
 'abating',
 'abattoi

In [ ]:
features_names = [features_names[i] for i in ch2.get_support(indices=True)]
features_names = np.asarray(features_names)
features_names[0]

'aa'

Kita akan fit data ke dalam model Multinomial Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
multi_nb_clf = MultinomialNB()
multi_nb_clf.fit(tfidf_nb_multi_train, train_data_label)
predict_multi_nb = multi_nb_clf.predict(tfidf_nb_multi_test)

Kita akan lihat performanya

In [ ]:
print('Classification Report for Multinomial NB Using Tf-Idf Vectorizer: \n\n', classification_report(test_data_label, predict_multi_nb, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Multinomial NB Using Tf-Idf Vectorizer: \n', confusion_matrix(test_data_label, predict_multi_nb))
print()
print('Model Accuracy for Multinomial NB Using Tf-Idf Vectorizer: ', accuracy_score(test_data_label, predict_multi_nb))

Classification Report for Multinomial NB Using Tf-Idf Vectorizer: 

               precision    recall  f1-score   support

    Negative       0.85      0.88      0.87      6157
    Positive       0.88      0.85      0.87      6343

    accuracy                           0.87     12500
   macro avg       0.87      0.87      0.87     12500
weighted avg       0.87      0.87      0.87     12500

Confusion Matrix for Multinomial NB Using Tf-Idf Vectorizer: 
 [[5424  733]
 [ 938 5405]]

Model Accuracy for Multinomial NB Using Tf-Idf Vectorizer:  0.86632


##### **Fifth Model : Multinomial Naive Bayes (Count Vectorizer with binary = False)**

In [ ]:
multi_nb_count_clf = MultinomialNB()
multi_nb_count_clf.fit(count_multi_nb_train, train_data_label)
predict_multi_nb_count = multi_nb_count_clf.predict(count_multi_nb_test)

In [ ]:
print('Classification Report for Multinomial Naive Bayes Using Count Vectorizer with binary = False: \n\n', classification_report(test_data_label, predict_multi_nb_count, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Multinomial Naive Bayes Using Count Vectorizer with binary = False: \n', confusion_matrix(test_data_label, predict_multi_nb_count))
print()
print('Model Accuracy for Multinomial Naive Bayes Using Count Vectorizer with binary = False: ', accuracy_score(test_data_label, predict_multi_nb_count))

Classification Report for Multinomial Naive Bayes Using Count Vectorizer with binary = False: 

               precision    recall  f1-score   support

    Negative       0.88      0.89      0.89      6157
    Positive       0.90      0.88      0.89      6343

    accuracy                           0.89     12500
   macro avg       0.89      0.89      0.89     12500
weighted avg       0.89      0.89      0.89     12500

Confusion Matrix for Multinomial Naive Bayes Using Count Vectorizer with binary = False: 
 [[5503  654]
 [ 752 5591]]

Model Accuracy for Multinomial Naive Bayes Using Count Vectorizer with binary = False:  0.88752


##### **Sixth Model : Multinomial Naive Bayes (Count Vectorizer with binary = True)**

In [ ]:
multi_nb_count_true_clf = MultinomialNB()
multi_nb_count_true_clf.fit(count_multi_nb_true_train, train_data_label)
predict_multi_nb_count_true = multi_nb_count_true_clf.predict(count_multi_nb_true_test)

In [ ]:
print('Classification Report for Multinomial Naive Bayes Using Count Vectorizer with binary = True: \n\n', classification_report(test_data_label, predict_multi_nb_count_true, target_names=['Negative', 'Positive']))
print('Confusion Matrix for Multinomial Naive Bayes Using Count Vectorizer with binary = True: \n', confusion_matrix(test_data_label, predict_multi_nb_count_true))
print()
print('Model Accuracy for Multinomial Naive Bayes Using Count Vectorizer with binary = True: ', accuracy_score(test_data_label, predict_multi_nb_count_true))

Classification Report for Multinomial Naive Bayes Using Count Vectorizer with binary = True: 

               precision    recall  f1-score   support

    Negative       0.88      0.90      0.89      6157
    Positive       0.90      0.88      0.89      6343

    accuracy                           0.89     12500
   macro avg       0.89      0.89      0.89     12500
weighted avg       0.89      0.89      0.89     12500

Confusion Matrix for Multinomial Naive Bayes Using Count Vectorizer with binary = True: 
 [[5572  585]
 [ 777 5566]]

Model Accuracy for Multinomial Naive Bayes Using Count Vectorizer with binary = True:  0.89104


Nilai Akurasi Tertinggi didapat dengan model **Multinomial Naive Bayes dengan Count Vectorizer memakai binary = True** 

Membandingkan dua model terbaik

In [ ]:
print('Nilai Akurasi Linear SVC dengan Tf-Idf Vectorizer adalah                                   : ', accuracy_score(test_data_label, predict_svc))
print('Nilai Akurasi Multinomial Naive Bayes dengan Count Vectorizer memakai binary = True adalah : ', accuracy_score(test_data_label, predict_multi_nb_count_true))

Nilai Akurasi Linear SVC dengan Tf-Idf Vectorizer adalah                                   :  0.90288
Nilai Akurasi Multinomial Naive Bayes dengan Count Vectorizer memakai binary = True adalah :  0.89104


Model Linear SVC dengan Tf-Idf Vectorizer memberikan nilai akurasi terbaik, sehingga kita akan menjadikannya sebagai model untuk dataset ini. Berikutnya kita akan melihat outcomenya

In [ ]:
dataset_predict = dataset_test.copy()
dataset_predict = pd.DataFrame(dataset_predict)
dataset_predict.columns = ['review']
dataset_predict = dataset_predict.reset_index()
dataset_predict.head()

index                                             review
0  33553  I really liked this Summerslam due to the look...
1   9427  Not many television shows appeal to quite as m...
2    199  The film quickly gets to a major chase scene w...
3  12447  Jane Austen would definitely approve of this o...
4  39489  Expectations were somewhat high for me when I ...

In [ ]:
dataset_predict = dataset_predict.drop(['index'], axis=1)
dataset_predict.head()

review
0  I really liked this Summerslam due to the look...
1  Not many television shows appeal to quite as m...
2  The film quickly gets to a major chase scene w...
3  Jane Austen would definitely approve of this o...
4  Expectations were somewhat high for me when I ...

In [ ]:
test_actual_label = test_data_label.copy()
test_actual_label = pd.DataFrame(test_actual_label)
test_actual_label.columns = ['sentiment']
test_actual_label['sentiment'] = test_actual_label['sentiment'].replace({1 : 'positive', 0 : 'negative'})

In [ ]:
test_predicted_label = predict_svc.copy()
test_predicted_label = pd.DataFrame(test_predicted_label)
test_predicted_label.columns = ['predicted_sentiment']
test_predicted_label['predicted_sentiment'] = test_predicted_label['predicted_sentiment'].replace({1 : 'positive', 0 : 'negative'})

In [ ]:
test_result = pd.concat([dataset_predict, test_actual_label, test_predicted_label], axis=1)
test_result.head()

review  ... predicted_sentiment
0  I really liked this Summerslam due to the look...  ...            negative
1  Not many television shows appeal to quite as m...  ...            positive
2  The film quickly gets to a major chase scene w...  ...            negative
3  Jane Austen would definitely approve of this o...  ...            positive
4  Expectations were somewhat high for me when I ...  ...            negative

[5 rows x 3 columns]

Berikut dapat dilihat hasil prediksi klasifikasi sentimen memakai Model Linear SVC yang divectorize dengan Tf-Idf Vectorizer. Berdasarkan nilai akurasi, sekitar 90% dari hasil real data bisa diprediksi dengan benar memakai model Linear SVC ini.